// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: tser/tracker.proto

package tser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlList []string `protobuf:"bytes,1,rep,name=urlList,proto3" json:"urlList,omitempty"`
}

func (x *ClientRegisterRequest) Reset() {
	*x = ClientRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tser_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisterRequest) ProtoMessage() {}

func (x *ClientRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tser_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisterRequest.ProtoReflect.Descriptor instead.
func (*ClientRegisterRequest) Descriptor() ([]byte, []int) {
	return file_tser_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *ClientRegisterRequest) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

type ClientRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrList []string `protobuf:"bytes,1,rep,name=errList,proto3" json:"errList,omitempty"`
}

func (x *ClientRegisterResponse) Reset() {
	*x = ClientRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tser_tracker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegisterResponse) ProtoMessage() {}

func (x *ClientRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tser_tracker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegisterResponse.ProtoReflect.Descriptor instead.
func (*ClientRegisterResponse) Descriptor() ([]byte, []int) {
	return file_tser_tracker_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRegisterResponse) GetErrList() []string {
	if x != nil {
		return x.ErrList
	}
	return nil
}

type GetPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPeerRequest) Reset() {
	*x = GetPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tser_tracker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerRequest) ProtoMessage() {}

func (x *GetPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tser_tracker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerRequest.ProtoReflect.Descriptor instead.
func (*GetPeerRequest) Descriptor() ([]byte, []int) {
	return file_tser_tracker_proto_rawDescGZIP(), []int{2}
}

type GetPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UrlList []string `protobuf:"bytes,1,rep,name=urlList,proto3" json:"urlList,omitempty"`
}

func (x *GetPeerResponse) Reset() {
	*x = GetPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tser_tracker_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerResponse) ProtoMessage() {}

func (x *GetPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tser_tracker_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerResponse.ProtoReflect.Descriptor instead.
func (*GetPeerResponse) Descriptor() ([]byte, []int) {
	return file_tser_tracker_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeerResponse) GetUrlList() []string {
	if x != nil {
		return x.UrlList
	}
	return nil
}

var File_tser_tracker_proto protoreflect.FileDescriptor

var file_tser_tracker_proto_rawDesc = []byte{
	0x0a, 0x12, 0x74, 0x73, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x74, 0x73, 0x65, 0x72, 0x22, 0x31, 0x0a, 0x15, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a,
	0x16, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x65, 0x72, 0x72, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x72, 0x6c, 0x4c, 0x69, 0x73, 0x74,
	0x32, 0x90, 0x01, 0x0a, 0x0b, 0x54, 0x73, 0x65, 0x72, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72,
	0x12, 0x47, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x74,
	0x73, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74,
	0x50, 0x65, 0x65, 0x72, 0x12, 0x14, 0x2e, 0x74, 0x73, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x74, 0x73, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x74, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tser_tracker_proto_rawDescOnce sync.Once
	file_tser_tracker_proto_rawDescData = file_tser_tracker_proto_rawDesc
)

func file_tser_tracker_proto_rawDescGZIP() []byte {
	file_tser_tracker_proto_rawDescOnce.Do(func() {
		file_tser_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_tser_tracker_proto_rawDescData)
	})
	return file_tser_tracker_proto_rawDescData
}

var file_tser_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tser_tracker_proto_goTypes = []interface{}{
	(*ClientRegisterRequest)(nil),  // 0: tser.ClientRegisterRequest
	(*ClientRegisterResponse)(nil), // 1: tser.ClientRegisterResponse
	(*GetPeerRequest)(nil),         // 2: tser.GetPeerRequest
	(*GetPeerResponse)(nil),        // 3: tser.GetPeerResponse
}
var file_tser_tracker_proto_depIdxs = []int32{
	0, // 0: tser.TserTracker.Register:input_type -> tser.ClientRegisterRequest
	2, // 1: tser.TserTracker.GetPeer:input_type -> tser.GetPeerRequest
	1, // 2: tser.TserTracker.Register:output_type -> tser.ClientRegisterResponse
	3, // 3: tser.TserTracker.GetPeer:output_type -> tser.GetPeerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tser_tracker_proto_init() }
func file_tser_tracker_proto_init() {
	if File_tser_tracker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tser_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tser_tracker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tser_tracker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tser_tracker_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tser_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tser_tracker_proto_goTypes,
		DependencyIndexes: file_tser_tracker_proto_depIdxs,
		MessageInfos:      file_tser_tracker_proto_msgTypes,
	}.Build()
	File_tser_tracker_proto = out.File
	file_tser_tracker_proto_rawDesc = nil
	file_tser_tracker_proto_goTypes = nil
	file_tser_tracker_proto_depIdxs = nil
}
